galaxy_info:
  author: Dominik Becker
  description: installs common dependencies for commerce infrastructure and configures general environment
  company: QSC AG
  issue_tracker_url: https://jira.one4all.lan/projects/HCSAP/issues/
  license: license (GPLv2, CC-BY, etc)
  min_ansible_version: 1.2
  platforms:
    - name: CentOS
      versions:
        - 7
  galaxy_tags: []
dependencies: []