---
# tasks file for k8s-reset
- name: run kubeadm reset
  shell: kubeadm reset --force
- name: stop kubelet
  systemd:
    name: kubelet
    enabled: yes
    daemon_reload: yes
    state: stopped
- name: stop docker daemon
  systemd:
    name: docker
    enabled: yes
    daemon_reload: yes
    state: stopped
- name: delete cni files (1)
  file:
    path: /var/lib/cni/
    state: absent
- name: delete cni files (2)
  file:
    path: /etc/cni/
    state: absent
- name: delete kubelet files
  file:
    path: /var/lib/kubelet/*
    state: absent
- name: disable cni0 net interface
  command: "ifconfig cni0 down"
  ignore_errors: yes
- name: disable flannel net interface
  command: "ifconfig flannel.1 down"
  ignore_errors: yes
- name: disable docker net interface
  command: "ifconfig docker0 down"
  ignore_errors: yes
- name: delete cni0 net interface
  command: "ip link delete cni0"
  ignore_errors: yes
- name: delete flannel net interface
  command: "ip link delete flannel.1"
  ignore_errors: yes
- name: reboot cluster
  reboot:
- name: stop kubelet
  systemd:
    name: kubelet
    enabled: yes
    daemon_reload: yes
    state: stopped
- name: stop docker daemon
  systemd:
    name: docker
    enabled: yes
    daemon_reload: yes
    state: stopped