---
# handlers file for k8s-install
- name: enable and restart docker daemon
  systemd:
    name: docker
    enabled: yes
    daemon_reload: yes
    state: restarted
- name: enable and restart kubelet
  systemd:
    name: kubelet
    enabled: yes
    daemon_reload: yes
    state: restarted